# Generated by Django 3.2.9 on 2021-11-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer2',
            old_name='layer2json',
            new_name='network',
        ),
    ]
