# Generated by Django 3.2.9 on 2021-11-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_rename_layer2json_layer2_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer2',
            name='name',
            field=models.CharField(default='network', max_length=10),
        ),
    ]
