# Generated by Django 3.2.9 on 2021-11-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0003_layer2_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer2',
            name='name',
        ),
    ]
