# Generated by Django 3.2.9 on 2021-11-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_remove_layer2_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer2',
            name='network',
            field=models.TextField(),
        ),
    ]
