# Generated by Django 3.2.9 on 2021-11-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0005_alter_layer2_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer2',
            name='network',
            field=models.JSONField(),
        ),
    ]
