# Generated by Django 3.2.9 on 2021-11-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0007_rename_network_layer2_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer2',
            name='id',
        ),
        migrations.AddField(
            model_name='layer2',
            name='NetworkID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
