# Generated by Django 3.2.9 on 2021-11-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0008_auto_20211119_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer2',
            name='NetworkID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
