# Generated by Django 3.2.9 on 2021-11-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0009_alter_layer2_networkid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer2',
            name='NetworkID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
