# Generated by Django 3.2.8 on 2021-12-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0012_alter_layer2_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VNFs',
            fields=[
                ('NetworkID', models.AutoField(primary_key=True, serialize=False)),
                ('Network', models.JSONField()),
            ],
            options={
                'get_latest_by': ['NetworkID'],
            },
        ),
    ]
