# Generated by Django 3.2.9 on 2022-01-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0013_vnfs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFCs',
            fields=[
                ('SFCListID', models.AutoField(primary_key=True, serialize=False)),
                ('SFCList', models.JSONField()),
            ],
            options={
                'get_latest_by': ['SFCListID'],
            },
        ),
    ]
